Script fixed and color added.

diff --git a/manga-cli b/manga-cli
--- a/manga-cli
+++ b/manga-cli
@@ -1,4 +1,11 @@
 #!/bin/sh
+
+red="$(tput setaf 1)"
+green="$(tput setaf 2)"
+yellow="$(tput setaf 3)"
+blue="$(tput setaf 4)"
+purple="$(tput setaf 5)"
+
 usage () {
     echo 'Usage:'
     echo ' -h    help text'
@@ -36,6 +43,7 @@ get_last_chapter () {
 get_chapter_images () {
     title="$1"
     chapter="$2"
+
     curl -s "https://mangabuddy.com/${title}/${chapter}" \
         -H 'authority: mangabuddy.com' \
         -H 'upgrade-insecure-requests: 1' \
@@ -50,8 +58,9 @@ get_chapter_images () {
     --compressed |
         grep -oP "[a-z0-9_]+\.jpg" |
         sort -u |
-        sed "s|^|https://static.youmadcdn.xyz/manga/${title}/${chapter}/|g"
+        sed "s|^|https://s1.madcdnv2.xyz/file/img-mbuddy/manga/${title}/${chapter}/|g"
 }
+
 
 chapters_matching_number () {
     chapter_number="$1"
@@ -72,24 +81,29 @@ clean_chaptername () {
 
     echo "${chaptername_prefix}${chaptername_suffix}"
 }
-
 download_image () {
     url="$1"
+    # curl -s "$url" \
+    #   -H 'authority: static.youmadcdn.xyz' \
+    #   -H 'pragma: no-cache' \
+    #   -H 'cache-control: no-cache' \
+    #   -H 'upgrade-insecure-requests: 1' \
+    #   -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36' \
+    #   -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
+    #   -H 'sec-gpc: 1' \
+    #   -H 'sec-fetch-site: cross-site' \
+    #   -H 'sec-fetch-mode: navigate' \
+    #   -H 'sec-fetch-user: ?1' \
+    #   -H 'sec-fetch-dest: document' \
+    #   -H 'referer: https://mangabuddy.com/' \
+    #   -H 'accept-language: en-US,en;q=0.9' \
+    #   --compressed
+
     curl -s "$url" \
-      -H 'authority: static.youmadcdn.xyz' \
-      -H 'pragma: no-cache' \
-      -H 'cache-control: no-cache' \
-      -H 'upgrade-insecure-requests: 1' \
-      -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36' \
-      -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
-      -H 'sec-gpc: 1' \
-      -H 'sec-fetch-site: cross-site' \
-      -H 'sec-fetch-mode: navigate' \
-      -H 'sec-fetch-user: ?1' \
-      -H 'sec-fetch-dest: document' \
-      -H 'referer: https://mangabuddy.com/' \
-      -H 'accept-language: en-US,en;q=0.9' \
-  --compressed
+        -H 'Upgrade-Insecure-Requests: 1' \
+        -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36' \
+        -H 'referer: https://mangabuddy.com/' \
+    --compressed
 }
 
 download_chapter () {
@@ -120,7 +134,7 @@ download_multiple_chapters () {
     for chapter_number in $(seq "$first_selected" "$last_selected"); do
         matching_chapters=$(chapters_matching_number "$chapter_number" "$chapters")
         for chapter in $matching_chapters; do
-            echo "Downloading chapter ${chapter_number}..."
+            echo "${blue}Downloading chapter ${chapter_number}..."
             download_chapter "$title" "$chapter" "$chapter_number"
         done
     done
@@ -131,16 +145,16 @@ check_inputs () {
     last_selected="$2"
     last_chapter="$3"
 
-    [ -z "$first_selected" ] && die "Invalid input"
-	[ "$first_selected" -eq "$first_selected" ] 2>/dev/null || die "Invalid number"
+    [ -z "$first_selected" ] && die "${red}Invalid input"
+	[ "$first_selected" -eq "$first_selected" ] 2>/dev/null || die "${red}Invalid number"
 
     if [ -n "$last_chapter" ]; then
-        [ "$last_selected" -eq "$last_selected" ] 2>/dev/null || die "Invalid number"
+        [ "$last_selected" -eq "$last_selected" ] 2>/dev/null || die "${red}Invalid number"
         if [ "$last_chapter" -lt "$last_selected" ]; then
-            die "Chapter out of range"
+            die "${red}Chapter out of range"
         fi
         if [ "$last_selected" -lt "$first_selected" ]; then
-            die "Invalid range"
+            die "${red}Invalid range"
         fi
     fi
 }
@@ -152,7 +166,7 @@ while getopts "ht:n" OPT; do
     "h") usage;exit;; # show help
     "t") query=$OPTARG;;
     "n") notshow=1;;
-    "?") die "Invalid parameter";;
+    "?") die "${red}Invalid parameter";;
   esac
 done
 
@@ -161,18 +175,18 @@ if [ -z "$query" ]; then
     read -r query
 fi
 
-echo "Searching title..."
+echo "${blue}Searching title..."
 response=$(search_title "$query")
 
-[ -z "$response" ] && die "No results found"
+[ -z "$response" ] && die "${red}No results found"
 
 title=$(echo "$response" | fzf)
 
 chapters=$(get_chapters_names "$title")
 last_chapter=$(get_last_chapter "$chapters")
 
-echo "Download a single chapter: chapter_number"
-echo "Download multiple chapters: first_chapter last_chapter"
+echo "${purple}Download a single chapter: ${yellow}chapter_number"
+echo "${purple}Download multiple chapters: ${yellow}first_chapter ${yellow}last_chapter${green}"
 printf "Available chapters (1-%d): " "${last_chapter}"
 read -r first_selected last_selected
 
